[build]
  functions = "netlify/functions"
  publish = "."
  included_files = ["sports-news.txt", "global-news.txt", "us-news.txt", "economy-mkts-news.txt", "popculture-news.txt", "*.txt"]

[[redirects]]
  from = "/sports-news-archive"
  to = "/sports-news-archive.html"
  status = 200
  force = true

[[redirects]]
  from = "/sports-news-archive/*"
  to = "/sports-news-archive.html"
  status = 200
  force = true

[[redirects]]
  from = "/global-news-archive"
  to = "/global-news-archive.html"
  status = 200
  force = true

[[redirects]]
  from = "/global-news-archive/*"
  to = "/global-news-archive.html"
  status = 200
  force = true

[[redirects]]
  from = "/us-news-archive"
  to = "/us-news-archive.html"
  status = 200
  force = true

[[redirects]]
  from = "/us-news-archive/*"
  to = "/us-news-archive.html"
  status = 200
  force = true

[[redirects]]
  from = "/economy-news-archive"
  to = "/economy-news-archive.html"
  status = 200
  force = true

[[redirects]]
  from = "/economy-news-archive/*"
  to = "/economy-news-archive.html"
  status = 200
  force = true

[[redirects]]
  from = "/popculture-news-archive"
  to = "/popculture-news-archive.html"
  status = 200
  force = true

[[redirects]]
  from = "/popculture-news-archive/*"
  to = "/popculture-news-archive.html"
  status = 200
  force = true
