backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "links"
    label: "Daily Links"
    folder: "_data"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Color", name: "color", widget: "select", options: ["c-blue", "c-green", "c-red", "c-orange", "c-pink", "c-indigo", "c-violet", "c-light-blue", "c-lime-green", "c-black", "c-purple"], default: "c-blue"}
      - {label: "Status", name: "status", widget: "select", options: ["active", "archived"], default: "active"}
      - {label: "Date Added", name: "date", widget: "datetime", default: "{{now}}"}
